name: Run Discord Bot

on:
  push:
    branches:
      - main  # Exécute le workflow à chaque push sur main
  schedule:
    - cron: "0 */5 * * *"  # Exécution automatique toutes les 5 heures

concurrency:
  group: bot-actions
  cancel-in-progress: true  # Annule les workflows en cours si un nouveau démarre

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Configurer l'environnement Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Version recommandée de Python

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 4 : Vérification des scripts
    - name: Verify all scripts exist
      run: |
        ls -la ./
        ls -la citations/
        ls -la shifumi/
        ls -la Règlement/
        if [ ! -f "bot.py" ]; then echo "Erreur : bot.py est manquant !" && exit 1; fi
        if [ ! -f "ia.py" ]; then echo "Erreur : ia.py est manquant !" && exit 1; fi
        if [ ! -f "citations/citations.py" ]; then echo "Erreur : citations.py est manquant !" && exit 1; fi
        if [ ! -f "citations/keywords.txt" ]; then echo "Erreur : keywords.txt est manquant !" && exit 1; fi
        if [ ! -f "citations/citations.txt" ]; then echo "Erreur : citations.txt est manquant !" && exit 1; fi
        if [ ! -f "shifumi/shifumi.py" ]; then echo "Erreur : shifumi.py est manquant !" && exit 1; fi
        if [ ! -f "Règlement/reglement.py" ]; then echo "Erreur : reglement.py est manquant !" && exit 1; fi

    # Étape 5 : Lancer le fichier principal (bot.py)
    - name: Run main bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_IA_TOKEN: ${{ secrets.DISCORD_IA_TOKEN }}
      run: |
        python bot.py

    # Étape 6 : Lancer le bot Citations
    - name: Run Citations bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: |
        python citations/citations.py

    # Étape 7 : Lancer le bot Shifumi
    - name: Run Shifumi bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: |
        python shifumi/shifumi.py

    # Étape 8 : Lancer le bot Règlement
    - name: Run Règlement bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: |
        python Règlement/reglement.py
