name: Run Discord Bot

on:
  push:
    branches:
      - main
  schedule:  # Exécution automatique toutes les 5 heures
    - cron: "0 */5 * * *"

concurrency:
  group: bot-actions
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot
      run: |
        echo DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} >> .env
        echo DISCORD_IA_TOKEN=${{ secrets.DISCORD_IA_TOKEN }} >> .env
        python citations/citations.py &       # Lancer citations.py en arrière-plan
        python Règlement/reglement.py &       # Lancer reglement.py en arrière-plan
        python shifumi/shifumi.py &           # Lancer shifumi.py en arrière-plan
        python bot.py                         # Lancer le fichier bot.py
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_IA_TOKEN: ${{ secrets.DISCORD_IA_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
