name: Run Discord Bot

on:
  push:
    branches:
      - main  # Exécute le workflow à chaque push sur main
  schedule:
    - cron: "0 */5 * * *"  # Exécution automatique toutes les 5 heures

concurrency:
  group: bot-actions
  cancel-in-progress: true  # Annule les workflows en cours si un nouveau démarre

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Configurer l'environnement Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Version recommandée de Python

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 4 : Vérifier que tous les fichiers sont présents
    - name: Verify all scripts exist
      run: |
        ls -la
        if [ ! -f "bot.py" ]; then echo "bot.py is missing!" && exit 1; fi
        if [ ! -f "Shifumi.py" ]; then echo "Shifumi.py is missing!" && exit 1; fi
        if [ ! -f "citation.py" ]; then echo "citation.py is missing!" && exit 1; fi

    # Étape 5 : Lancer le fichier bot principal
    - name: Run main bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_IA_TOKEN: ${{ secrets.DISCORD_IA_TOKEN }}
      run: |
        python bot.py

    # Étape 6 : Lancer le fichier Shifumi
    - name: Run Shifumi bot
      if: always()  # Toujours exécuter cette étape
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: |
        python Shifumi.py

    # Étape 7 : Lancer le fichier Citations bot
    - name: Run Citations bot
      if: always()
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: |
        python citation.py
